import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { config } from './config';
import { getSettings } from './settings';

/**
 * Sold-state overlay.
 *
 * Lives OUTSIDE data/catalog.json on purpose: the catalogue is regenerated by
 * `npm run normalize`, and sold state must survive that. The Etsy sync (and,
 * once checkout lands, our own order flow) writes here; the catalogue reader
 * overlays it at query time. One source of truth for "is this stone sold",
 * shared by both sales channels.
 *
 * Shape: { [etsyId]: soldAtISO }
 */
const PATH = join(config.paths.var, 'sold.json');

let cache: { at: number; value: Record<string, string> } | null = null;

export function soldMap(): Record<string, string> {
  if (cache && Date.now() - cache.at < 5000) return cache.value;
  let value: Record<string, string> = {};
  try {
    if (existsSync(PATH)) value = JSON.parse(readFileSync(PATH, 'utf8'));
  } catch {
    value = {};
  }
  cache = { at: Date.now(), value };
  return value;
}

export async function markSold(etsyIds: string[], soldAt = new Date().toISOString()) {
  const map = { ...soldMap() };
  for (const id of etsyIds) map[id] ??= soldAt;
  await mkdir(dirname(PATH), { recursive: true });
  await writeFile(PATH, JSON.stringify(map, null, 2), 'utf8');
  cache = null;
}

export async function unmarkSold(etsyId: string) {
  const map = { ...soldMap() };
  delete map[etsyId];
  await mkdir(dirname(PATH), { recursive: true });
  await writeFile(PATH, JSON.stringify(map, null, 2), 'utf8');
  cache = null;
}

/** Sold, but still within the admin-configured display window. */
export function isSoldDisplayable(soldAt: string): boolean {
  const days = getSettings().soldDisplayDays;
  return Date.now() - new Date(soldAt).getTime() <= days * 86400_000;
}

/** Sold and past the display window: drop from listings entirely. */
export function isSoldExpired(soldAt: string): boolean {
  return !isSoldDisplayable(soldAt);
}
